/** ISO 3166-1 alpha-2 country codes with default billing/display currency (ISO 4217). */
export const COUNTRY_CATALOG = [
  { code: "AF", label: "Afghanistan", currency: "AFN" },
  { code: "AL", label: "Albania", currency: "EUR" },
  { code: "DZ", label: "Algeria", currency: "DZD" },
  { code: "AD", label: "Andorra", currency: "EUR" },
  { code: "AO", label: "Angola", currency: "AOA" },
  { code: "AR", label: "Argentina", currency: "ARS" },
  { code: "AM", label: "Armenia", currency: "AMD" },
  { code: "AU", label: "Australia", currency: "AUD" },
  { code: "AT", label: "Austria", currency: "EUR" },
  { code: "AZ", label: "Azerbaijan", currency: "AZN" },
  { code: "BH", label: "Bahrain", currency: "BHD" },
  { code: "BD", label: "Bangladesh", currency: "BDT" },
  { code: "BY", label: "Belarus", currency: "BYN" },
  { code: "BE", label: "Belgium", currency: "EUR" },
  { code: "BZ", label: "Belize", currency: "BZD" },
  { code: "BJ", label: "Benin", currency: "XOF" },
  { code: "BT", label: "Bhutan", currency: "BTN" },
  { code: "BO", label: "Bolivia", currency: "BOB" },
  { code: "BA", label: "Bosnia and Herzegovina", currency: "BAM" },
  { code: "BW", label: "Botswana", currency: "BWP" },
  { code: "BR", label: "Brazil", currency: "BRL" },
  { code: "BN", label: "Brunei", currency: "BND" },
  { code: "BG", label: "Bulgaria", currency: "BGN" },
  { code: "BF", label: "Burkina Faso", currency: "XOF" },
  { code: "BI", label: "Burundi", currency: "BIF" },
  { code: "KH", label: "Cambodia", currency: "KHR" },
  { code: "CM", label: "Cameroon", currency: "XAF" },
  { code: "CA", label: "Canada", currency: "CAD" },
  { code: "CV", label: "Cape Verde", currency: "CVE" },
  { code: "CF", label: "Central African Republic", currency: "XAF" },
  { code: "TD", label: "Chad", currency: "XAF" },
  { code: "CL", label: "Chile", currency: "CLP" },
  { code: "CN", label: "China", currency: "CNY" },
  { code: "CO", label: "Colombia", currency: "COP" },
  { code: "KM", label: "Comoros", currency: "KMF" },
  { code: "CG", label: "Congo", currency: "XAF" },
  { code: "CD", label: "Congo (DRC)", currency: "CDF" },
  { code: "CR", label: "Costa Rica", currency: "CRC" },
  { code: "CI", label: "Côte d'Ivoire", currency: "XOF" },
  { code: "HR", label: "Croatia", currency: "EUR" },
  { code: "CU", label: "Cuba", currency: "CUP" },
  { code: "CY", label: "Cyprus", currency: "EUR" },
  { code: "CZ", label: "Czech Republic", currency: "CZK" },
  { code: "DK", label: "Denmark", currency: "DKK" },
  { code: "DJ", label: "Djibouti", currency: "DJF" },
  { code: "DO", label: "Dominican Republic", currency: "DOP" },
  { code: "EC", label: "Ecuador", currency: "USD" },
  { code: "EG", label: "Egypt", currency: "EGP" },
  { code: "SV", label: "El Salvador", currency: "USD" },
  { code: "GQ", label: "Equatorial Guinea", currency: "XAF" },
  { code: "ER", label: "Eritrea", currency: "ERN" },
  { code: "EE", label: "Estonia", currency: "EUR" },
  { code: "SZ", label: "Eswatini", currency: "SZL" },
  { code: "ET", label: "Ethiopia", currency: "ETB" },
  { code: "FI", label: "Finland", currency: "EUR" },
  { code: "FR", label: "France", currency: "EUR" },
  { code: "GA", label: "Gabon", currency: "XAF" },
  { code: "GM", label: "Gambia", currency: "GMD" },
  { code: "GE", label: "Georgia", currency: "GEL" },
  { code: "DE", label: "Germany", currency: "EUR" },
  { code: "GH", label: "Ghana", currency: "GHS" },
  { code: "GR", label: "Greece", currency: "EUR" },
  { code: "GT", label: "Guatemala", currency: "GTQ" },
  { code: "GN", label: "Guinea", currency: "GNF" },
  { code: "GW", label: "Guinea-Bissau", currency: "XOF" },
  { code: "GY", label: "Guyana", currency: "GYD" },
  { code: "HT", label: "Haiti", currency: "HTG" },
  { code: "HN", label: "Honduras", currency: "HNL" },
  { code: "HK", label: "Hong Kong", currency: "HKD" },
  { code: "HU", label: "Hungary", currency: "HUF" },
  { code: "IS", label: "Iceland", currency: "ISK" },
  { code: "IN", label: "India", currency: "INR" },
  { code: "ID", label: "Indonesia", currency: "IDR" },
  { code: "IR", label: "Iran", currency: "IRR" },
  { code: "IQ", label: "Iraq", currency: "IQD" },
  { code: "IE", label: "Ireland", currency: "EUR" },
  { code: "IL", label: "Israel", currency: "ILS" },
  { code: "IT", label: "Italy", currency: "EUR" },
  { code: "JM", label: "Jamaica", currency: "JMD" },
  { code: "JP", label: "Japan", currency: "JPY" },
  { code: "JO", label: "Jordan", currency: "JOD" },
  { code: "KZ", label: "Kazakhstan", currency: "KZT" },
  { code: "KE", label: "Kenya", currency: "KES" },
  { code: "KW", label: "Kuwait", currency: "KWD" },
  { code: "KG", label: "Kyrgyzstan", currency: "KGS" },
  { code: "LA", label: "Laos", currency: "LAK" },
  { code: "LV", label: "Latvia", currency: "EUR" },
  { code: "LB", label: "Lebanon", currency: "LBP" },
  { code: "LS", label: "Lesotho", currency: "LSL" },
  { code: "LR", label: "Liberia", currency: "LRD" },
  { code: "LY", label: "Libya", currency: "LYD" },
  { code: "LI", label: "Liechtenstein", currency: "CHF" },
  { code: "LT", label: "Lithuania", currency: "EUR" },
  { code: "LU", label: "Luxembourg", currency: "EUR" },
  { code: "MO", label: "Macau", currency: "MOP" },
  { code: "MG", label: "Madagascar", currency: "MGA" },
  { code: "MW", label: "Malawi", currency: "MWK" },
  { code: "MY", label: "Malaysia", currency: "MYR" },
  { code: "MV", label: "Maldives", currency: "MVR" },
  { code: "ML", label: "Mali", currency: "XOF" },
  { code: "MT", label: "Malta", currency: "EUR" },
  { code: "MR", label: "Mauritania", currency: "MRU" },
  { code: "MU", label: "Mauritius", currency: "MUR" },
  { code: "MX", label: "Mexico", currency: "MXN" },
  { code: "MD", label: "Moldova", currency: "MDL" },
  { code: "MC", label: "Monaco", currency: "EUR" },
  { code: "MN", label: "Mongolia", currency: "MNT" },
  { code: "ME", label: "Montenegro", currency: "EUR" },
  { code: "MA", label: "Morocco", currency: "MAD" },
  { code: "MZ", label: "Mozambique", currency: "MZN" },
  { code: "MM", label: "Myanmar", currency: "MMK" },
  { code: "NA", label: "Namibia", currency: "NAD" },
  { code: "NP", label: "Nepal", currency: "NPR" },
  { code: "NL", label: "Netherlands", currency: "EUR" },
  { code: "NZ", label: "New Zealand", currency: "NZD" },
  { code: "NI", label: "Nicaragua", currency: "NIO" },
  { code: "NE", label: "Niger", currency: "XOF" },
  { code: "NG", label: "Nigeria", currency: "NGN" },
  { code: "MK", label: "North Macedonia", currency: "MKD" },
  { code: "NO", label: "Norway", currency: "NOK" },
  { code: "OM", label: "Oman", currency: "OMR" },
  { code: "PK", label: "Pakistan", currency: "PKR" },
  { code: "PS", label: "Palestine", currency: "ILS" },
  { code: "PA", label: "Panama", currency: "PAB" },
  { code: "PG", label: "Papua New Guinea", currency: "PGK" },
  { code: "PY", label: "Paraguay", currency: "PYG" },
  { code: "PE", label: "Peru", currency: "PEN" },
  { code: "PH", label: "Philippines", currency: "PHP" },
  { code: "PL", label: "Poland", currency: "PLN" },
  { code: "PT", label: "Portugal", currency: "EUR" },
  { code: "QA", label: "Qatar", currency: "QAR" },
  { code: "RO", label: "Romania", currency: "RON" },
  { code: "RU", label: "Russia", currency: "RUB" },
  { code: "RW", label: "Rwanda", currency: "RWF" },
  { code: "SA", label: "Saudi Arabia", currency: "SAR" },
  { code: "SN", label: "Senegal", currency: "XOF" },
  { code: "RS", label: "Serbia", currency: "RSD" },
  { code: "SC", label: "Seychelles", currency: "SCR" },
  { code: "SL", label: "Sierra Leone", currency: "SLE" },
  { code: "SG", label: "Singapore", currency: "SGD" },
  { code: "SK", label: "Slovakia", currency: "EUR" },
  { code: "SI", label: "Slovenia", currency: "EUR" },
  { code: "SO", label: "Somalia", currency: "SOS" },
  { code: "ZA", label: "South Africa", currency: "ZAR" },
  { code: "KR", label: "South Korea", currency: "KRW" },
  { code: "SS", label: "South Sudan", currency: "SSP" },
  { code: "ES", label: "Spain", currency: "EUR" },
  { code: "LK", label: "Sri Lanka", currency: "LKR" },
  { code: "SD", label: "Sudan", currency: "SDG" },
  { code: "SR", label: "Suriname", currency: "SRD" },
  { code: "SE", label: "Sweden", currency: "SEK" },
  { code: "CH", label: "Switzerland", currency: "CHF" },
  { code: "SY", label: "Syria", currency: "SYP" },
  { code: "TW", label: "Taiwan", currency: "TWD" },
  { code: "TJ", label: "Tajikistan", currency: "TJS" },
  { code: "TZ", label: "Tanzania", currency: "TZS" },
  { code: "TH", label: "Thailand", currency: "THB" },
  { code: "TL", label: "Timor-Leste", currency: "USD" },
  { code: "TG", label: "Togo", currency: "XOF" },
  { code: "TT", label: "Trinidad and Tobago", currency: "TTD" },
  { code: "TN", label: "Tunisia", currency: "TND" },
  { code: "TR", label: "Turkey", currency: "TRY" },
  { code: "TM", label: "Turkmenistan", currency: "TMT" },
  { code: "UG", label: "Uganda", currency: "UGX" },
  { code: "UA", label: "Ukraine", currency: "UAH" },
  { code: "AE", label: "United Arab Emirates", currency: "AED" },
  { code: "GB", label: "United Kingdom", currency: "GBP" },
  { code: "US", label: "United States", currency: "USD" },
  { code: "UY", label: "Uruguay", currency: "UYU" },
  { code: "UZ", label: "Uzbekistan", currency: "UZS" },
  { code: "VE", label: "Venezuela", currency: "VES" },
  { code: "VN", label: "Vietnam", currency: "VND" },
  { code: "YE", label: "Yemen", currency: "YER" },
  { code: "ZM", label: "Zambia", currency: "ZMW" },
  { code: "ZW", label: "Zimbabwe", currency: "ZWL" },
  { code: "OTHER", label: "Other / not listed", currency: "USD" },
] as const;

export type PricingCountry = (typeof COUNTRY_CATALOG)[number]["code"];

const currencyLabels: Record<string, string> = {
  INR: "INR — Indian Rupee",
  USD: "USD — US Dollar",
  AED: "AED — UAE Dirham",
  SAR: "SAR — Saudi Riyal",
  BHD: "BHD — Bahraini Dinar",
  OMR: "OMR — Omani Rial",
  QAR: "QAR — Qatari Riyal",
  KWD: "KWD — Kuwaiti Dinar",
  GBP: "GBP — British Pound",
  EUR: "EUR — Euro",
  SGD: "SGD — Singapore Dollar",
  CAD: "CAD — Canadian Dollar",
  AUD: "AUD — Australian Dollar",
  JPY: "JPY — Japanese Yen",
  CNY: "CNY — Chinese Yuan",
  HKD: "HKD — Hong Kong Dollar",
  CHF: "CHF — Swiss Franc",
  ZAR: "ZAR — South African Rand",
  NGN: "NGN — Nigerian Naira",
  EGP: "EGP — Egyptian Pound",
  PKR: "PKR — Pakistani Rupee",
  BDT: "BDT — Bangladeshi Taka",
  NPR: "NPR — Nepalese Rupee",
  LKR: "LKR — Sri Lankan Rupee",
  MYR: "MYR — Malaysian Ringgit",
  THB: "THB — Thai Baht",
  IDR: "IDR — Indonesian Rupiah",
  PHP: "PHP — Philippine Peso",
  KRW: "KRW — South Korean Won",
  TRY: "TRY — Turkish Lira",
  RUB: "RUB — Russian Ruble",
  BRL: "BRL — Brazilian Real",
  MXN: "MXN — Mexican Peso",
  PLN: "PLN — Polish Zloty",
  SEK: "SEK — Swedish Krona",
  NOK: "NOK — Norwegian Krone",
  DKK: "DKK — Danish Krone",
  NZD: "NZD — New Zealand Dollar",
};

const catalogCurrencies = [...new Set(COUNTRY_CATALOG.map((row) => row.currency))].sort();

export const currencyOptions = catalogCurrencies.map((value) => ({
  value,
  label: currencyLabels[value] ?? value,
}));

export type PricingCurrency = (typeof currencyOptions)[number]["value"];

export const countryOptions = COUNTRY_CATALOG.map((row) => ({
  value: row.code,
  label: row.label,
  defaultCurrency: row.currency as PricingCurrency,
}));

/** Approximate INR per 1 unit of foreign currency (for marketing price display). */
export const inrPerCurrencyUnit: Record<string, number> = {
  INR: 1,
  USD: 83,
  AED: 22.6,
  SAR: 22.1,
  BHD: 220,
  OMR: 215,
  QAR: 22.8,
  KWD: 270,
  GBP: 105,
  EUR: 90,
  SGD: 62,
  CAD: 61,
  AUD: 54,
  JPY: 0.55,
  CNY: 11.5,
  HKD: 10.6,
  CHF: 95,
  ZAR: 4.5,
  NGN: 0.055,
  EGP: 1.7,
  PKR: 0.3,
  BDT: 0.75,
  NPR: 0.62,
  LKR: 0.28,
  MYR: 18,
  THB: 2.3,
  IDR: 0.0052,
  PHP: 1.45,
  KRW: 0.062,
  TRY: 2.6,
  RUB: 0.9,
  BRL: 16,
  MXN: 4.8,
  PLN: 21,
  SEK: 7.8,
  NOK: 7.6,
  DKK: 12,
  NZD: 50,
};

export const currencyLocale: Record<string, string> = {
  INR: "en-IN",
  USD: "en-US",
  AED: "en-AE",
  SAR: "ar-SA",
  BHD: "ar-BH",
  OMR: "ar-OM",
  QAR: "ar-QA",
  KWD: "ar-KW",
  GBP: "en-GB",
  EUR: "en-IE",
  SGD: "en-SG",
};

export function getCountryDefaultCurrency(country: PricingCountry): PricingCurrency {
  return (
    countryOptions.find((option) => option.value === country)?.defaultCurrency ??
    ("USD" as PricingCurrency)
  );
}

export function getInrPerUnit(currency: string): number {
  return inrPerCurrencyUnit[currency] ?? inrPerCurrencyUnit.USD ?? 83;
}
