/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnavailableRouteImport } from './routes/unavailable'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as QuoteTokenRouteImport } from './routes/quote.$token'
import { Route as PlatformLoginRouteImport } from './routes/platform.login'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSalesCrmRouteImport } from './routes/app.sales-crm'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProcurementRouteImport } from './routes/app.procurement'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppHrRouteImport } from './routes/app.hr'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppBranchesRouteImport } from './routes/app.branches'
import { Route as AppBillingPosRouteImport } from './routes/app.billing-pos'
import { Route as AppAutomationsRouteImport } from './routes/app.automations'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAiCopilotRouteImport } from './routes/app.ai-copilot'
import { Route as AppAccountingRouteImport } from './routes/app.accounting'
import { Route as AdminWebsiteRouteImport } from './routes/admin.website'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUnavailableRouteImport } from './routes/admin.unavailable'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSalesPartnersRouteImport } from './routes/admin.sales-partners'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminInfrastructureRouteImport } from './routes/admin.infrastructure'
import { Route as AdminComplianceRouteImport } from './routes/admin.compliance'
import { Route as AdminAutomationsRouteImport } from './routes/admin.automations'
import { Route as AdminAlertsLogsRouteImport } from './routes/admin.alerts-logs'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppInvoicesIndexRouteImport } from './routes/app.invoices.index'
import { Route as AppInventoryIndexRouteImport } from './routes/app.inventory.index'
import { Route as AppHrIndexRouteImport } from './routes/app.hr.index'
import { Route as AppCrmIndexRouteImport } from './routes/app.crm.index'
import { Route as AppSettingsBillingRouteImport } from './routes/app.settings.billing'
import { Route as AppSettingsAdminRouteImport } from './routes/app.settings.admin'
import { Route as AppInvoicesCreateRouteImport } from './routes/app.invoices.create'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/app.invoices.$invoiceId'
import { Route as AppInventoryWarehousesRouteImport } from './routes/app.inventory.warehouses'
import { Route as AppInventoryProductsRouteImport } from './routes/app.inventory.products'
import { Route as AppInventoryCategoriesRouteImport } from './routes/app.inventory.categories'
import { Route as AppHrPayrollRouteImport } from './routes/app.hr.payroll'
import { Route as AppHrLeaveRouteImport } from './routes/app.hr.leave'
import { Route as AppHrEmployeesRouteImport } from './routes/app.hr.employees'
import { Route as AppHrAttendanceRouteImport } from './routes/app.hr.attendance'
import { Route as AppCrmTemplatesRouteImport } from './routes/app.crm.templates'
import { Route as AppCrmQuotationsRouteImport } from './routes/app.crm.quotations'
import { Route as AppCrmProposalsRouteImport } from './routes/app.crm.proposals'
import { Route as AppCrmPipelinesRouteImport } from './routes/app.crm.pipelines'
import { Route as AppCrmOpportunitiesRouteImport } from './routes/app.crm.opportunities'
import { Route as AppCrmLeadsRouteImport } from './routes/app.crm.leads'
import { Route as AppCrmAssetsRouteImport } from './routes/app.crm.assets'
import { Route as AdminSettingsEmailRouteImport } from './routes/admin.settings.email'
import { Route as AppCrmQuotationsQuotationIdRouteImport } from './routes/app.crm.quotations.$quotationId'

const UnavailableRoute = UnavailableRouteImport.update({
  id: '/unavailable',
  path: '/unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const QuoteTokenRoute = QuoteTokenRouteImport.update({
  id: '/quote/$token',
  path: '/quote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformLoginRoute = PlatformLoginRouteImport.update({
  id: '/platform/login',
  path: '/platform/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesCrmRoute = AppSalesCrmRouteImport.update({
  id: '/sales-crm',
  path: '/sales-crm',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingPosRoute = AppBillingPosRouteImport.update({
  id: '/billing-pos',
  path: '/billing-pos',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCopilotRoute = AppAiCopilotRouteImport.update({
  id: '/ai-copilot',
  path: '/ai-copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnavailableRoute = AdminUnavailableRouteImport.update({
  id: '/unavailable',
  path: '/unavailable',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesPartnersRoute = AdminSalesPartnersRouteImport.update({
  id: '/sales-partners',
  path: '/sales-partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfrastructureRoute = AdminInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplianceRoute = AdminComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationsRoute = AdminAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsLogsRoute = AdminAlertsLogsRouteImport.update({
  id: '/alerts-logs',
  path: '/alerts-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppHrIndexRoute = AppHrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHrRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAdminRoute = AppSettingsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppInvoicesCreateRoute = AppInvoicesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInventoryWarehousesRoute = AppInventoryWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryProductsRoute = AppInventoryProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryCategoriesRoute = AppInventoryCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppHrPayrollRoute = AppHrPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrLeaveRoute = AppHrLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrEmployeesRoute = AppHrEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrAttendanceRoute = AppHrAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppHrRoute,
} as any)
const AppCrmTemplatesRoute = AppCrmTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmQuotationsRoute = AppCrmQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmProposalsRoute = AppCrmProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmPipelinesRoute = AppCrmPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmOpportunitiesRoute = AppCrmOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmLeadsRoute = AppCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmAssetsRoute = AppCrmAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppCrmRoute,
} as any)
const AdminSettingsEmailRoute = AdminSettingsEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AppCrmQuotationsQuotationIdRoute =
  AppCrmQuotationsQuotationIdRouteImport.update({
    id: '/$quotationId',
    path: '/$quotationId',
    getParentRoute: () => AppCrmQuotationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/unavailable': typeof UnavailableRoute
  '/admin/alerts-logs': typeof AdminAlertsLogsRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-partners': typeof AdminSalesPartnersRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/unavailable': typeof AdminUnavailableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/ai-copilot': typeof AppAiCopilotRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/billing-pos': typeof AppBillingPosRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/hr': typeof AppHrRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/invoices': typeof AppInvoicesRouteWithChildren
  '/app/procurement': typeof AppProcurementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales-crm': typeof AppSalesCrmRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/suppliers': typeof AppSuppliersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/platform/login': typeof PlatformLoginRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/settings/email': typeof AdminSettingsEmailRoute
  '/app/crm/assets': typeof AppCrmAssetsRoute
  '/app/crm/leads': typeof AppCrmLeadsRoute
  '/app/crm/opportunities': typeof AppCrmOpportunitiesRoute
  '/app/crm/pipelines': typeof AppCrmPipelinesRoute
  '/app/crm/proposals': typeof AppCrmProposalsRoute
  '/app/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/app/crm/templates': typeof AppCrmTemplatesRoute
  '/app/hr/attendance': typeof AppHrAttendanceRoute
  '/app/hr/employees': typeof AppHrEmployeesRoute
  '/app/hr/leave': typeof AppHrLeaveRoute
  '/app/hr/payroll': typeof AppHrPayrollRoute
  '/app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/app/inventory/products': typeof AppInventoryProductsRoute
  '/app/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/app/invoices/create': typeof AppInvoicesCreateRoute
  '/app/settings/admin': typeof AppSettingsAdminRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/crm/': typeof AppCrmIndexRoute
  '/app/hr/': typeof AppHrIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/crm/quotations/$quotationId': typeof AppCrmQuotationsQuotationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/unavailable': typeof UnavailableRoute
  '/admin/alerts-logs': typeof AdminAlertsLogsRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-partners': typeof AdminSalesPartnersRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/unavailable': typeof AdminUnavailableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/ai-copilot': typeof AppAiCopilotRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/billing-pos': typeof AppBillingPosRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales-crm': typeof AppSalesCrmRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/platform/login': typeof PlatformLoginRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/settings/email': typeof AdminSettingsEmailRoute
  '/app/crm/assets': typeof AppCrmAssetsRoute
  '/app/crm/leads': typeof AppCrmLeadsRoute
  '/app/crm/opportunities': typeof AppCrmOpportunitiesRoute
  '/app/crm/pipelines': typeof AppCrmPipelinesRoute
  '/app/crm/proposals': typeof AppCrmProposalsRoute
  '/app/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/app/crm/templates': typeof AppCrmTemplatesRoute
  '/app/hr/attendance': typeof AppHrAttendanceRoute
  '/app/hr/employees': typeof AppHrEmployeesRoute
  '/app/hr/leave': typeof AppHrLeaveRoute
  '/app/hr/payroll': typeof AppHrPayrollRoute
  '/app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/app/inventory/products': typeof AppInventoryProductsRoute
  '/app/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/app/invoices/create': typeof AppInvoicesCreateRoute
  '/app/settings/admin': typeof AppSettingsAdminRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/crm': typeof AppCrmIndexRoute
  '/app/hr': typeof AppHrIndexRoute
  '/app/inventory': typeof AppInventoryIndexRoute
  '/app/invoices': typeof AppInvoicesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/crm/quotations/$quotationId': typeof AppCrmQuotationsQuotationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/unavailable': typeof UnavailableRoute
  '/admin/alerts-logs': typeof AdminAlertsLogsRoute
  '/admin/automations': typeof AdminAutomationsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales-partners': typeof AdminSalesPartnersRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/unavailable': typeof AdminUnavailableRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/ai-copilot': typeof AppAiCopilotRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/billing-pos': typeof AppBillingPosRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/hr': typeof AppHrRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/invoices': typeof AppInvoicesRouteWithChildren
  '/app/procurement': typeof AppProcurementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales-crm': typeof AppSalesCrmRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/suppliers': typeof AppSuppliersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/platform/login': typeof PlatformLoginRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/settings/email': typeof AdminSettingsEmailRoute
  '/app/crm/assets': typeof AppCrmAssetsRoute
  '/app/crm/leads': typeof AppCrmLeadsRoute
  '/app/crm/opportunities': typeof AppCrmOpportunitiesRoute
  '/app/crm/pipelines': typeof AppCrmPipelinesRoute
  '/app/crm/proposals': typeof AppCrmProposalsRoute
  '/app/crm/quotations': typeof AppCrmQuotationsRouteWithChildren
  '/app/crm/templates': typeof AppCrmTemplatesRoute
  '/app/hr/attendance': typeof AppHrAttendanceRoute
  '/app/hr/employees': typeof AppHrEmployeesRoute
  '/app/hr/leave': typeof AppHrLeaveRoute
  '/app/hr/payroll': typeof AppHrPayrollRoute
  '/app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/app/inventory/products': typeof AppInventoryProductsRoute
  '/app/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/app/invoices/create': typeof AppInvoicesCreateRoute
  '/app/settings/admin': typeof AppSettingsAdminRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/crm/': typeof AppCrmIndexRoute
  '/app/hr/': typeof AppHrIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/crm/quotations/$quotationId': typeof AppCrmQuotationsQuotationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/contact'
    | '/demo'
    | '/features'
    | '/forbidden'
    | '/forgot-password'
    | '/help'
    | '/industries'
    | '/login'
    | '/partner'
    | '/portal'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/unavailable'
    | '/admin/alerts-logs'
    | '/admin/automations'
    | '/admin/compliance'
    | '/admin/infrastructure'
    | '/admin/integrations'
    | '/admin/reports'
    | '/admin/sales-partners'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/tenants'
    | '/admin/unavailable'
    | '/admin/users'
    | '/admin/website'
    | '/app/accounting'
    | '/app/ai-copilot'
    | '/app/alerts'
    | '/app/automations'
    | '/app/billing-pos'
    | '/app/branches'
    | '/app/crm'
    | '/app/customers'
    | '/app/documents'
    | '/app/hr'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/procurement'
    | '/app/reports'
    | '/app/sales-crm'
    | '/app/settings'
    | '/app/suppliers'
    | '/invite/$token'
    | '/platform/login'
    | '/quote/$token'
    | '/admin/'
    | '/app/'
    | '/admin/settings/email'
    | '/app/crm/assets'
    | '/app/crm/leads'
    | '/app/crm/opportunities'
    | '/app/crm/pipelines'
    | '/app/crm/proposals'
    | '/app/crm/quotations'
    | '/app/crm/templates'
    | '/app/hr/attendance'
    | '/app/hr/employees'
    | '/app/hr/leave'
    | '/app/hr/payroll'
    | '/app/inventory/categories'
    | '/app/inventory/products'
    | '/app/inventory/warehouses'
    | '/app/invoices/$invoiceId'
    | '/app/invoices/create'
    | '/app/settings/admin'
    | '/app/settings/billing'
    | '/app/crm/'
    | '/app/hr/'
    | '/app/inventory/'
    | '/app/invoices/'
    | '/app/settings/'
    | '/app/crm/quotations/$quotationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/demo'
    | '/features'
    | '/forbidden'
    | '/forgot-password'
    | '/help'
    | '/industries'
    | '/login'
    | '/partner'
    | '/portal'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/unavailable'
    | '/admin/alerts-logs'
    | '/admin/automations'
    | '/admin/compliance'
    | '/admin/infrastructure'
    | '/admin/integrations'
    | '/admin/reports'
    | '/admin/sales-partners'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/tenants'
    | '/admin/unavailable'
    | '/admin/users'
    | '/admin/website'
    | '/app/accounting'
    | '/app/ai-copilot'
    | '/app/alerts'
    | '/app/automations'
    | '/app/billing-pos'
    | '/app/branches'
    | '/app/customers'
    | '/app/documents'
    | '/app/procurement'
    | '/app/reports'
    | '/app/sales-crm'
    | '/app/suppliers'
    | '/invite/$token'
    | '/platform/login'
    | '/quote/$token'
    | '/admin'
    | '/app'
    | '/admin/settings/email'
    | '/app/crm/assets'
    | '/app/crm/leads'
    | '/app/crm/opportunities'
    | '/app/crm/pipelines'
    | '/app/crm/proposals'
    | '/app/crm/quotations'
    | '/app/crm/templates'
    | '/app/hr/attendance'
    | '/app/hr/employees'
    | '/app/hr/leave'
    | '/app/hr/payroll'
    | '/app/inventory/categories'
    | '/app/inventory/products'
    | '/app/inventory/warehouses'
    | '/app/invoices/$invoiceId'
    | '/app/invoices/create'
    | '/app/settings/admin'
    | '/app/settings/billing'
    | '/app/crm'
    | '/app/hr'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/settings'
    | '/app/crm/quotations/$quotationId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/contact'
    | '/demo'
    | '/features'
    | '/forbidden'
    | '/forgot-password'
    | '/help'
    | '/industries'
    | '/login'
    | '/partner'
    | '/portal'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/unavailable'
    | '/admin/alerts-logs'
    | '/admin/automations'
    | '/admin/compliance'
    | '/admin/infrastructure'
    | '/admin/integrations'
    | '/admin/reports'
    | '/admin/sales-partners'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/tenants'
    | '/admin/unavailable'
    | '/admin/users'
    | '/admin/website'
    | '/app/accounting'
    | '/app/ai-copilot'
    | '/app/alerts'
    | '/app/automations'
    | '/app/billing-pos'
    | '/app/branches'
    | '/app/crm'
    | '/app/customers'
    | '/app/documents'
    | '/app/hr'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/procurement'
    | '/app/reports'
    | '/app/sales-crm'
    | '/app/settings'
    | '/app/suppliers'
    | '/invite/$token'
    | '/platform/login'
    | '/quote/$token'
    | '/admin/'
    | '/app/'
    | '/admin/settings/email'
    | '/app/crm/assets'
    | '/app/crm/leads'
    | '/app/crm/opportunities'
    | '/app/crm/pipelines'
    | '/app/crm/proposals'
    | '/app/crm/quotations'
    | '/app/crm/templates'
    | '/app/hr/attendance'
    | '/app/hr/employees'
    | '/app/hr/leave'
    | '/app/hr/payroll'
    | '/app/inventory/categories'
    | '/app/inventory/products'
    | '/app/inventory/warehouses'
    | '/app/invoices/$invoiceId'
    | '/app/invoices/create'
    | '/app/settings/admin'
    | '/app/settings/billing'
    | '/app/crm/'
    | '/app/hr/'
    | '/app/inventory/'
    | '/app/invoices/'
    | '/app/settings/'
    | '/app/crm/quotations/$quotationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  FeaturesRoute: typeof FeaturesRoute
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  PortalRoute: typeof PortalRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  UnavailableRoute: typeof UnavailableRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PlatformLoginRoute: typeof PlatformLoginRoute
  QuoteTokenRoute: typeof QuoteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unavailable': {
      id: '/unavailable'
      path: '/unavailable'
      fullPath: '/unavailable'
      preLoaderRoute: typeof UnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/quote/$token': {
      id: '/quote/$token'
      path: '/quote/$token'
      fullPath: '/quote/$token'
      preLoaderRoute: typeof QuoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/login': {
      id: '/platform/login'
      path: '/platform/login'
      fullPath: '/platform/login'
      preLoaderRoute: typeof PlatformLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales-crm': {
      id: '/app/sales-crm'
      path: '/sales-crm'
      fullPath: '/app/sales-crm'
      preLoaderRoute: typeof AppSalesCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/procurement': {
      id: '/app/procurement'
      path: '/procurement'
      fullPath: '/app/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr': {
      id: '/app/hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branches': {
      id: '/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing-pos': {
      id: '/app/billing-pos'
      path: '/billing-pos'
      fullPath: '/app/billing-pos'
      preLoaderRoute: typeof AppBillingPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automations': {
      id: '/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-copilot': {
      id: '/app/ai-copilot'
      path: '/ai-copilot'
      fullPath: '/app/ai-copilot'
      preLoaderRoute: typeof AppAiCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounting': {
      id: '/app/accounting'
      path: '/accounting'
      fullPath: '/app/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unavailable': {
      id: '/admin/unavailable'
      path: '/unavailable'
      fullPath: '/admin/unavailable'
      preLoaderRoute: typeof AdminUnavailableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales-partners': {
      id: '/admin/sales-partners'
      path: '/sales-partners'
      fullPath: '/admin/sales-partners'
      preLoaderRoute: typeof AdminSalesPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infrastructure': {
      id: '/admin/infrastructure'
      path: '/infrastructure'
      fullPath: '/admin/infrastructure'
      preLoaderRoute: typeof AdminInfrastructureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compliance': {
      id: '/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AdminComplianceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automations': {
      id: '/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AdminAutomationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts-logs': {
      id: '/admin/alerts-logs'
      path: '/alerts-logs'
      fullPath: '/admin/alerts-logs'
      preLoaderRoute: typeof AdminAlertsLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/invoices/': {
      id: '/app/invoices/'
      path: '/'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/app/inventory/': {
      id: '/app/inventory/'
      path: '/'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/hr/': {
      id: '/app/hr/'
      path: '/'
      fullPath: '/app/hr/'
      preLoaderRoute: typeof AppHrIndexRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/app/crm/': {
      id: '/app/crm/'
      path: '/'
      fullPath: '/app/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/admin': {
      id: '/app/settings/admin'
      path: '/admin'
      fullPath: '/app/settings/admin'
      preLoaderRoute: typeof AppSettingsAdminRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/invoices/create': {
      id: '/app/invoices/create'
      path: '/create'
      fullPath: '/app/invoices/create'
      preLoaderRoute: typeof AppInvoicesCreateRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/app/invoices/$invoiceId': {
      id: '/app/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/app/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/app/inventory/warehouses': {
      id: '/app/inventory/warehouses'
      path: '/warehouses'
      fullPath: '/app/inventory/warehouses'
      preLoaderRoute: typeof AppInventoryWarehousesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/products': {
      id: '/app/inventory/products'
      path: '/products'
      fullPath: '/app/inventory/products'
      preLoaderRoute: typeof AppInventoryProductsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/categories': {
      id: '/app/inventory/categories'
      path: '/categories'
      fullPath: '/app/inventory/categories'
      preLoaderRoute: typeof AppInventoryCategoriesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/hr/payroll': {
      id: '/app/hr/payroll'
      path: '/payroll'
      fullPath: '/app/hr/payroll'
      preLoaderRoute: typeof AppHrPayrollRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/app/hr/leave': {
      id: '/app/hr/leave'
      path: '/leave'
      fullPath: '/app/hr/leave'
      preLoaderRoute: typeof AppHrLeaveRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/app/hr/employees': {
      id: '/app/hr/employees'
      path: '/employees'
      fullPath: '/app/hr/employees'
      preLoaderRoute: typeof AppHrEmployeesRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/app/hr/attendance': {
      id: '/app/hr/attendance'
      path: '/attendance'
      fullPath: '/app/hr/attendance'
      preLoaderRoute: typeof AppHrAttendanceRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/app/crm/templates': {
      id: '/app/crm/templates'
      path: '/templates'
      fullPath: '/app/crm/templates'
      preLoaderRoute: typeof AppCrmTemplatesRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/crm/quotations': {
      id: '/app/crm/quotations'
      path: '/quotations'
      fullPath: '/app/crm/quotations'
      preLoaderRoute: typeof AppCrmQuotationsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/crm/proposals': {
      id: '/app/crm/proposals'
      path: '/proposals'
      fullPath: '/app/crm/proposals'
      preLoaderRoute: typeof AppCrmProposalsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/crm/pipelines': {
      id: '/app/crm/pipelines'
      path: '/pipelines'
      fullPath: '/app/crm/pipelines'
      preLoaderRoute: typeof AppCrmPipelinesRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/crm/opportunities': {
      id: '/app/crm/opportunities'
      path: '/opportunities'
      fullPath: '/app/crm/opportunities'
      preLoaderRoute: typeof AppCrmOpportunitiesRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/crm/leads': {
      id: '/app/crm/leads'
      path: '/leads'
      fullPath: '/app/crm/leads'
      preLoaderRoute: typeof AppCrmLeadsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/crm/assets': {
      id: '/app/crm/assets'
      path: '/assets'
      fullPath: '/app/crm/assets'
      preLoaderRoute: typeof AppCrmAssetsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/admin/settings/email': {
      id: '/admin/settings/email'
      path: '/email'
      fullPath: '/admin/settings/email'
      preLoaderRoute: typeof AdminSettingsEmailRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/app/crm/quotations/$quotationId': {
      id: '/app/crm/quotations/$quotationId'
      path: '/$quotationId'
      fullPath: '/app/crm/quotations/$quotationId'
      preLoaderRoute: typeof AppCrmQuotationsQuotationIdRouteImport
      parentRoute: typeof AppCrmQuotationsRoute
    }
  }
}

interface AdminSettingsRouteChildren {
  AdminSettingsEmailRoute: typeof AdminSettingsEmailRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsEmailRoute: AdminSettingsEmailRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminRouteChildren {
  AdminAlertsLogsRoute: typeof AdminAlertsLogsRoute
  AdminAutomationsRoute: typeof AdminAutomationsRoute
  AdminComplianceRoute: typeof AdminComplianceRoute
  AdminInfrastructureRoute: typeof AdminInfrastructureRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalesPartnersRoute: typeof AdminSalesPartnersRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUnavailableRoute: typeof AdminUnavailableRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebsiteRoute: typeof AdminWebsiteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsLogsRoute: AdminAlertsLogsRoute,
  AdminAutomationsRoute: AdminAutomationsRoute,
  AdminComplianceRoute: AdminComplianceRoute,
  AdminInfrastructureRoute: AdminInfrastructureRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalesPartnersRoute: AdminSalesPartnersRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUnavailableRoute: AdminUnavailableRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebsiteRoute: AdminWebsiteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCrmQuotationsRouteChildren {
  AppCrmQuotationsQuotationIdRoute: typeof AppCrmQuotationsQuotationIdRoute
}

const AppCrmQuotationsRouteChildren: AppCrmQuotationsRouteChildren = {
  AppCrmQuotationsQuotationIdRoute: AppCrmQuotationsQuotationIdRoute,
}

const AppCrmQuotationsRouteWithChildren =
  AppCrmQuotationsRoute._addFileChildren(AppCrmQuotationsRouteChildren)

interface AppCrmRouteChildren {
  AppCrmAssetsRoute: typeof AppCrmAssetsRoute
  AppCrmLeadsRoute: typeof AppCrmLeadsRoute
  AppCrmOpportunitiesRoute: typeof AppCrmOpportunitiesRoute
  AppCrmPipelinesRoute: typeof AppCrmPipelinesRoute
  AppCrmProposalsRoute: typeof AppCrmProposalsRoute
  AppCrmQuotationsRoute: typeof AppCrmQuotationsRouteWithChildren
  AppCrmTemplatesRoute: typeof AppCrmTemplatesRoute
  AppCrmIndexRoute: typeof AppCrmIndexRoute
}

const AppCrmRouteChildren: AppCrmRouteChildren = {
  AppCrmAssetsRoute: AppCrmAssetsRoute,
  AppCrmLeadsRoute: AppCrmLeadsRoute,
  AppCrmOpportunitiesRoute: AppCrmOpportunitiesRoute,
  AppCrmPipelinesRoute: AppCrmPipelinesRoute,
  AppCrmProposalsRoute: AppCrmProposalsRoute,
  AppCrmQuotationsRoute: AppCrmQuotationsRouteWithChildren,
  AppCrmTemplatesRoute: AppCrmTemplatesRoute,
  AppCrmIndexRoute: AppCrmIndexRoute,
}

const AppCrmRouteWithChildren =
  AppCrmRoute._addFileChildren(AppCrmRouteChildren)

interface AppHrRouteChildren {
  AppHrAttendanceRoute: typeof AppHrAttendanceRoute
  AppHrEmployeesRoute: typeof AppHrEmployeesRoute
  AppHrLeaveRoute: typeof AppHrLeaveRoute
  AppHrPayrollRoute: typeof AppHrPayrollRoute
  AppHrIndexRoute: typeof AppHrIndexRoute
}

const AppHrRouteChildren: AppHrRouteChildren = {
  AppHrAttendanceRoute: AppHrAttendanceRoute,
  AppHrEmployeesRoute: AppHrEmployeesRoute,
  AppHrLeaveRoute: AppHrLeaveRoute,
  AppHrPayrollRoute: AppHrPayrollRoute,
  AppHrIndexRoute: AppHrIndexRoute,
}

const AppHrRouteWithChildren = AppHrRoute._addFileChildren(AppHrRouteChildren)

interface AppInventoryRouteChildren {
  AppInventoryCategoriesRoute: typeof AppInventoryCategoriesRoute
  AppInventoryProductsRoute: typeof AppInventoryProductsRoute
  AppInventoryWarehousesRoute: typeof AppInventoryWarehousesRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryCategoriesRoute: AppInventoryCategoriesRoute,
  AppInventoryProductsRoute: AppInventoryProductsRoute,
  AppInventoryWarehousesRoute: AppInventoryWarehousesRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppInvoicesRouteChildren {
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppInvoicesCreateRoute: typeof AppInvoicesCreateRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppInvoicesCreateRoute: AppInvoicesCreateRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAdminRoute: typeof AppSettingsAdminRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAdminRoute: AppSettingsAdminRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppAiCopilotRoute: typeof AppAiCopilotRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppBillingPosRoute: typeof AppBillingPosRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppCrmRoute: typeof AppCrmRouteWithChildren
  AppCustomersRoute: typeof AppCustomersRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppHrRoute: typeof AppHrRouteWithChildren
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppProcurementRoute: typeof AppProcurementRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesCrmRoute: typeof AppSalesCrmRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppAiCopilotRoute: AppAiCopilotRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppBillingPosRoute: AppBillingPosRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppCrmRoute: AppCrmRouteWithChildren,
  AppCustomersRoute: AppCustomersRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppHrRoute: AppHrRouteWithChildren,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppProcurementRoute: AppProcurementRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesCrmRoute: AppSalesCrmRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  FeaturesRoute: FeaturesRoute,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  PortalRoute: PortalRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  UnavailableRoute: UnavailableRoute,
  InviteTokenRoute: InviteTokenRoute,
  PlatformLoginRoute: PlatformLoginRoute,
  QuoteTokenRoute: QuoteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
