import { VelonRole } from './velon-role';
export declare const API_VERSION = "v1";
export { VELON_CONTACT_ADDRESS, VELON_CONTACT_EMAIL, VELON_CONTACT_PHONE } from './velon-contact';
export { COUNTRY_CATALOG, CURRENCY_SYMBOLS, DATE_FORMAT_OPTIONS, NUMBER_FORMAT_OPTIONS, TIMEZONE_OPTIONS, defaultDateFormatForCountry, defaultNumberFormatForCountry, defaultTimezoneForCountry, formatCurrencyLabel, formatWorkspaceMoney, getCountryByCode, getCountryDefaultCurrency, getCurrencySymbol, isKnownCountryCode, isKnownCurrencyCode, type CountryCode, type WorkspaceMoneyFormat, } from './localization';
export { VelonRole, normalizeVelonRole } from './velon-role';
export type AuthScope = 'platform' | 'tenant';
export declare const ROLE_PERMISSIONS: Record<VelonRole, string[]>;
export declare function isPlatformRole(role: VelonRole | string): boolean;
export declare function isTenantRole(role: VelonRole | string): boolean;
export declare function roleHasPermission(role: VelonRole, permission: string): boolean;
export type JwtPayload = {
    sub: string;
    email: string;
    scope: AuthScope;
    role: VelonRole;
    tenantId?: string;
    workspaceId?: string;
    membershipId?: string;
};
export type AuthTokens = {
    accessToken: string;
    refreshToken: string;
    expiresIn: number;
};
export { SEAT_LIMITS, seatLimitForPlan, isUnlimitedSeats, seatsRemaining, canAddSeat, } from './seats';
export { PLAN_CATALOG, planCatalogEntry, type PlanCatalogEntry } from './plans';
export { isIndiaBilling, planRegionalPricesFromDefinition, resolvePlanPrice, type PlanRegionalPrices, type PricingRegion, type ResolvedPlanPrice, } from './plan-pricing';
export { PASSWORD_MIN_LENGTH, PASSWORD_RULES, evaluatePasswordRules, isPasswordStrong, passwordStrengthMessage, type PasswordRuleId, type PasswordRuleStatus, } from './password-policy';
export { PAYMENT_PROVIDERS, TRIAL_DAYS_DEFAULT, ANNUAL_BILLING_MONTHS, BILLING_PORTAL_PATH_PREFIXES, yearlyPriceFromMonthly, mrrForPlan, normalizeApiPath, isBillingPortalPath, subscriptionAllowsWorkspaceAccess, subscriptionAllowsBillingPortal, mapSubscriptionStatusToTenantStatus, type BillingInterval, type SubscriptionBillingStatus, type PaymentProviderId, } from './billing';
export { WORKSPACE_SIDEBAR_LABELS, classifyDashboardLoaderError, isWorkspaceNavItemActive, normalizeWorkspacePath, workspaceNavHasDuplicateCrm, type DashboardErrorKind, } from './workspace-navigation';
export { WORKSPACE_ROLE_PRESETS, backendRoleToPresetLabel, rolePresetById, type RolePreset, type RolePresetId, } from './role-presets';
export { isAdminNavItemActive } from './admin-navigation';
export { DEMO_SEED_SOURCES, canSeedDemoTenants, inferDemoSeedSourceFromEmail, inferDemoSeedSourceFromTenantName, isDemoSeedSource, type DemoSeedSource, } from './seed-guards';
export { isProductionPlatformUser, isProductionTenant, productionPlatformUserWhere, productionTenantWhere, } from './production-data';
export { DEFAULT_WORKSPACE_PUBLIC_DOMAIN, resolveWorkspacePublicDomain, tenantWorkspaceHost, } from './workspace-host';
export { TENANT_STATUS_COLUMN_HELP, TENANT_STATUS_DESCRIPTIONS } from './tenant-status-help';
export { SETTINGS_PATHS, SETTINGS_USER_TABS, WORKSPACE_ADMIN_SECTIONS, canManageWorkspaceBilling, canManageWorkspaceSettings, parseSettingsUserTab, parseWorkspaceAdminSection, settingsBillingSearch, workspaceAdminSearch, type SettingsUserTab, type WorkspaceAdminSection, } from './settings-routes';
export { canReadCrm, canWriteCrmRecords, canManageCrmCustomers, canWriteCrmNotes, canWriteCrmActivities, canManageCrmActivities, } from './crm-permissions';
export { canReadInventory, canManageInventory } from './inventory-permissions';
export { canReadProcurement, canManageProcurement, canApproveProcurement, } from './procurement-permissions';
export { canReadSales, canWriteSales } from './sales-permissions';
